"""
medical_knowledge.py - expandable A-Z medical knowledge content.

The content here is intentionally structured rather than prose-only so each
subject can power notes, revision cards, MCQs, OSCE prompts, and bookmarks.
"""

from __future__ import annotations


def _subject(
    category,
    chapters,
    high_yield,
    clinical,
    diseases,
    drugs,
    mnemonics,
    osce,
    diagrams,
    tables,
    refs,
):
    return {
        "category": category,
        "chapters": chapters,
        "high_yield": high_yield,
        "clinical_correlations": clinical,
        "important_diagrams": diagrams,
        "tables": tables,
        "common_diseases": diseases,
        "drug_charts": drugs,
        "flashcards": [
            f"What is the must-know concept in {chapters[0]}?",
            f"Name one clinical correlation for {chapters[min(1, len(chapters)-1)]}.",
            f"List two exam traps in {chapters[-1]}.",
        ],
        "mcqs": [
            {
                "stem": f"A student is reviewing {chapters[0]}. Which finding is most high-yield?",
                "answer": high_yield[0],
                "explanation": "Focus first on mechanisms, classic presentations, and discriminating features.",
            }
        ],
        "osce_practical_skills": osce,
        "important_mnemonics": mnemonics,
        "references_resources": refs,
        "quick_revision_notes": [
            "Define the core mechanism before memorising exceptions.",
            "Link every fact to a patient presentation, investigation, or management decision.",
            "Revise with active recall: one-liners, diagrams, tables, then MCQs.",
        ],
        "high_yield_summaries": [
            f"{chapters[0]}: {high_yield[0]}",
            f"{chapters[-1]}: {clinical[0]}",
        ],
    }


AZ_MEDICAL_KNOWLEDGE = {
    "Anatomy": _subject(
        "Pre-clinical",
        ["Upper limb and brachial plexus", "Thorax and mediastinum", "Abdomen and pelvis", "Head, neck, and neuroanatomy"],
        ["Brachial plexus roots C5-T1 form trunks, divisions, cords, and terminal branches.", "Femoral triangle order lateral to medial is nerve, artery, vein, canal.", "Cavernous sinus lesions affect CN III, IV, V1, V2, VI and sympathetic fibers."],
        ["Wrist drop suggests radial nerve injury at the humeral shaft.", "Shoulder dislocation can injure the axillary nerve.", "Raised intracranial pressure may compress CN VI because of its long intracranial course."],
        ["Carpal tunnel syndrome", "Erb palsy", "Femoral hernia", "Subdural hematoma"],
        ["Local anesthetic nerve blocks: lidocaine, bupivacaine; know toxicity and safe dosing."],
        ["Randy Travis Drinks Cold Beer: roots, trunks, divisions, cords, branches.", "Some Lovers Try Positions That They Can't Handle: carpal bones."],
        ["Cranial nerve exam", "Peripheral nerve motor and sensory exam", "Abdominal surface anatomy"],
        ["Brachial plexus", "Circle of Willis", "Inguinal canal", "Cranial nerve nuclei"],
        ["Upper limb nerve lesions", "Cranial nerves and foramina", "Abdominal organ blood supply"],
        ["Gray's Anatomy for Students", "TeachMeAnatomy", "Acland anatomy videos"],
    ),
    "Physiology": _subject(
        "Pre-clinical",
        ["Cardiovascular physiology", "Respiratory mechanics", "Renal handling", "Endocrine feedback"],
        ["Cardiac output equals heart rate multiplied by stroke volume.", "Type I respiratory failure is hypoxemia; type II includes hypercapnia.", "GFR is regulated by afferent and efferent arteriolar tone."],
        ["Heart failure reflects impaired preload, afterload, contractility, or rhythm.", "COPD causes air trapping and increased residual volume.", "Primary endocrine disease moves hormone and feedback hormone in opposite directions."],
        ["Heart failure", "Asthma", "Chronic kidney disease", "Diabetes mellitus"],
        ["Beta blockers reduce heart rate and renin release; ACE inhibitors dilate efferent arteriole."],
        ["CO = HR x SV.", "ROME: Respiratory Opposite, Metabolic Equal for acid-base compensation."],
        ["Blood pressure measurement", "Peak flow assessment", "Fluid balance chart interpretation"],
        ["Wigger diagram", "Spirometry loops", "Nephron transport map", "HPA axis"],
        ["Acid-base disorders", "Lung volumes", "Cardiac cycle events"],
        ["Guyton and Hall", "Costanzo Physiology", "Khan Academy Medicine"],
    ),
    "Biochemistry": _subject(
        "Pre-clinical",
        ["Glycolysis and TCA", "Lipid metabolism", "Amino acids and urea cycle", "Molecular biology"],
        ["Glycolysis produces net 2 ATP and 2 NADH per glucose.", "Urea cycle defects cause hyperammonemia.", "B12 deficiency causes megaloblastic anemia and neurologic disease."],
        ["DKA increases ketone body production.", "Statins inhibit HMG-CoA reductase.", "PCR amplifies DNA using heat-stable polymerase."],
        ["Phenylketonuria", "G6PD deficiency", "Maple syrup urine disease", "Familial hypercholesterolemia"],
        ["Statins, fibrates, niacin, ezetimibe; know mechanism and key adverse effects."],
        ["4 Ds of pellagra: dermatitis, diarrhea, dementia, death.", "Can't See: vitamin C deficiency causes scurvy."],
        ["Explain an inherited metabolic disorder pedigree", "Interpret LFT and lipid results"],
        ["Glycolysis pathway", "Urea cycle", "DNA replication fork", "Lipoprotein metabolism"],
        ["Vitamins and deficiencies", "Enzyme inhibition patterns", "Amino acid disorders"],
        ["Lippincott Biochemistry", "Harper's Illustrated Biochemistry", "AMBOSS library"],
    ),
    "Pathology": _subject(
        "Pre-clinical",
        ["Cell injury", "Inflammation", "Neoplasia", "Systemic pathology"],
        ["Reversible injury shows cellular swelling; irreversible injury causes membrane damage.", "Granulomas suggest chronic inflammation driven by macrophages.", "Malignant tumors invade and metastasize."],
        ["Myocardial infarction evolves from coagulative necrosis to scar.", "Caseating granulomas suggest tuberculosis.", "Nephrotic syndrome causes heavy proteinuria and edema."],
        ["Atherosclerosis", "Pneumonia", "Tuberculosis", "Colorectal carcinoma"],
        ["Anti-inflammatory drugs: NSAIDs inhibit COX; corticosteroids inhibit phospholipase A2 signaling."],
        ["The 5 cardinal signs: pain, heat, redness, swelling, loss of function."],
        ["Describe a pathology specimen", "Interpret CBC and inflammatory markers"],
        ["Necrosis patterns", "Tumor spread routes", "Glomerular lesions"],
        ["Benign vs malignant tumors", "Acute vs chronic inflammation", "Nephritic vs nephrotic syndrome"],
        ["Robbins Basic Pathology", "Pathoma", "WHO tumor classifications"],
    ),
    "Pharmacology": _subject(
        "Pre-clinical",
        ["Pharmacokinetics", "Autonomic drugs", "Cardiovascular drugs", "Antimicrobials"],
        ["Competitive antagonists shift dose-response curves right.", "ACE inhibitors can cause cough, hyperkalemia, and fetal toxicity.", "Aminoglycosides can cause nephrotoxicity and ototoxicity."],
        ["Renal impairment requires dose adjustment for many drugs.", "Asthma can worsen with nonselective beta blockers.", "Warfarin is monitored with INR."],
        ["Hypertension", "Asthma", "Diabetes", "Bacterial sepsis"],
        ["ACE inhibitors, ARBs, CCBs, beta blockers, thiazides; beta-lactams, macrolides, quinolones."],
        ["SLUDGE for muscarinic excess.", "ABC: aminoglycosides bind 30S, chloramphenicol/macrolides/clindamycin bind 50S."],
        ["Medication history", "Prescription safety check", "Explain inhaler technique"],
        ["Dose-response curve", "Autonomic receptor map", "Antibiotic mechanism chart"],
        ["Antihypertensive classes", "Antibiotics by mechanism", "CYP450 interactions"],
        ["Katzung Pharmacology", "BNF", "Lexicomp/UpToDate drug monographs"],
    ),
    "Microbiology": _subject(
        "Pre-clinical",
        ["Bacteriology", "Virology", "Mycology", "Parasitology"],
        ["Gram-positive organisms retain crystal violet; gram-negative organisms have LPS outer membrane.", "Enveloped viruses are sensitive to drying and detergents.", "Malaria diagnosis uses thick and thin blood films."],
        ["Brucellosis can follow unpasteurized dairy exposure.", "Pseudomonas is associated with burns and ventilators.", "Dengue causes fever, thrombocytopenia, and plasma leakage risk."],
        ["Tuberculosis", "Brucellosis", "Malaria", "Dengue", "Candidiasis"],
        ["Penicillins, cephalosporins, vancomycin, aminoglycosides, macrolides, metronidazole."],
        ["Some Nasty Killers Have Some Capsule Protection: encapsulated bacteria.", "TORCH infections: toxoplasma, others, rubella, CMV, HSV."],
        ["Hand hygiene station", "Culture interpretation", "Fever in returning traveler history"],
        ["Gram stain algorithm", "Viral genome classification", "Malaria life cycle"],
        ["Antibiotic coverage", "Opportunistic infections", "Vaccine types"],
        ["Jawetz Microbiology", "CDC Yellow Book", "WHO infectious disease resources"],
    ),
    "Immunology": _subject(
        "Pre-clinical",
        ["Innate immunity", "Adaptive immunity", "Complement", "Hypersensitivity"],
        ["IgM is first response; IgG crosses placenta.", "MHC I presents to CD8 T cells; MHC II presents to CD4 T cells.", "Type I hypersensitivity is IgE-mediated."],
        ["C3 deficiency predisposes to recurrent pyogenic infections.", "DiGeorge syndrome causes T-cell deficiency.", "Anaphylaxis requires intramuscular adrenaline."],
        ["SLE", "Anaphylaxis", "SCID", "Common variable immunodeficiency"],
        ["Adrenaline, antihistamines, corticosteroids, biologics such as anti-TNF and anti-CD20 therapies."],
        ["ACID: MHC I to CD8.", "Type II hypersensitivity is antibody-mediated against cells or receptors."],
        ["Anaphylaxis management", "Vaccination counselling", "Autoimmune history"],
        ["Complement cascade", "Antibody structure", "Hypersensitivity types"],
        ["Immunoglobulin classes", "Primary immunodeficiencies", "Cytokines"],
        ["Abbas Immunology", "British Society for Immunology", "UpToDate immunology"],
    ),
    "Genetics": _subject(
        "Pre-clinical",
        ["Mendelian inheritance", "Chromosomal disorders", "Population genetics", "Genomic testing"],
        ["Autosomal dominant disease often appears in every generation.", "X-linked recessive disease commonly affects males.", "Trisomy 21 risk increases with maternal age."],
        ["BRCA variants increase breast and ovarian cancer risk.", "Consanguinity increases autosomal recessive disease risk.", "Pharmacogenomics can guide drug choice and dosing."],
        ["Down syndrome", "Turner syndrome", "Cystic fibrosis", "Thalassemia"],
        ["Folic acid prevents neural tube defects; hydroxyurea may be used in sickle cell disease."],
        ["AD every generation; AR siblings; XLR males.", "Hardy-Weinberg: p squared plus 2pq plus q squared equals 1."],
        ["Draw a pedigree", "Genetic counselling station", "Explain screening vs diagnostic testing"],
        ["Pedigree symbols", "Karyotype", "Meiosis nondisjunction"],
        ["Inheritance patterns", "Chromosomal syndromes", "Genetic tests"],
        ["Thompson & Thompson Genetics", "GeneReviews", "OMIM"],
    ),
    "Embryology": _subject(
        "Pre-clinical",
        ["Gametogenesis", "Germ layers", "Organogenesis", "Congenital anomalies"],
        ["Neural tube closes in week 4.", "Neural crest forms peripheral nerves, melanocytes, and adrenal medulla.", "Teratogen timing determines anomaly pattern."],
        ["Folate reduces neural tube defect risk.", "Failure of neural crest migration causes Hirschsprung disease.", "Rubella can cause cataracts, PDA, and deafness."],
        ["Neural tube defects", "Tetralogy of Fallot", "Hirschsprung disease", "Cleft palate"],
        ["Folic acid; avoid isotretinoin, valproate, warfarin, ACE inhibitors in pregnancy."],
        ["Ectoderm is attracted to the outside: skin and nervous system.", "Lateral plate mesoderm forms limb skeleton and cardiovascular structures."],
        ["Antenatal counselling", "Newborn congenital anomaly explanation"],
        ["Germ layer derivatives", "Pharyngeal arches", "Heart tube looping"],
        ["Teratogens by trimester", "Pharyngeal arch derivatives", "Germ layer derivatives"],
        ["Langman's Embryology", "Moore Embryology", "ACOG patient resources"],
    ),
    "Histology": _subject(
        "Pre-clinical",
        ["Epithelia", "Connective tissue", "Muscle and nerve", "Organ histology"],
        ["Simple squamous epithelium supports diffusion.", "Goblet cells secrete mucus.", "Plasma cells have clock-face chromatin and basophilic cytoplasm."],
        ["Barrett esophagus is intestinal metaplasia.", "Celiac disease causes villous atrophy.", "Hyaline membranes suggest neonatal respiratory distress syndrome."],
        ["Celiac disease", "Barrett esophagus", "Cirrhosis", "Glomerulonephritis"],
        ["Histology-linked stains: H&E, PAS, trichrome, silver stains; know what each highlights."],
        ["Pseudostratified epithelium looks layered but every cell touches basement membrane."],
        ["Microscope slide description", "Identify tissue type", "Explain biopsy result"],
        ["Nephron histology", "GI tract layers", "Liver lobule", "Respiratory epithelium"],
        ["Epithelium types", "Connective tissue cells", "Special stains"],
        ["Junqueira Histology", "Blue Histology", "University virtual microscopy collections"],
    ),
    "Neuroscience": _subject(
        "Pre-clinical",
        ["Neuroanatomy", "Motor pathways", "Sensory systems", "Higher cortical function"],
        ["Upper motor neuron lesions cause weakness, hyperreflexia, and spasticity.", "Dorsal columns carry vibration and proprioception.", "Broca aphasia is nonfluent with preserved comprehension."],
        ["Lateral medullary syndrome spares corticospinal tract.", "Parkinson disease reflects dopaminergic neuron loss in substantia nigra.", "Multiple sclerosis causes CNS demyelination."],
        ["Stroke", "Parkinson disease", "Multiple sclerosis", "Epilepsy"],
        ["Levodopa, dopamine agonists, antiepileptics, thrombolysis when eligible."],
        ["DANISH: dorsal column carries vibration, proprioception, fine touch.", "FAST: face, arm, speech, time for stroke."],
        ["Full neurologic exam", "Cranial nerve exam", "Stroke assessment"],
        ["Spinal tracts", "Basal ganglia loops", "Circle of Willis", "Language cortex"],
        ["UMN vs LMN signs", "Stroke syndromes", "Antiepileptic adverse effects"],
        ["Neuroanatomy Through Clinical Cases", "NICE stroke guidelines", "AAN resources"],
    ),
    "Behavioral Science": _subject(
        "Pre-clinical",
        ["Learning theory", "Doctor-patient communication", "Ethics", "Biostatistics"],
        ["Sensitivity rules out when negative; specificity rules in when positive.", "Capacity is decision-specific and can fluctuate.", "Open questions improve patient-centered histories."],
        ["Motivational interviewing supports smoking cessation.", "Confidentiality can be breached for serious safety risk.", "Bias can distort clinical decision-making."],
        ["Substance use disorder", "Depression", "Anxiety", "Burnout"],
        ["SSRIs, nicotine replacement, varenicline, benzodiazepines with caution."],
        ["SPIKES for breaking bad news.", "SPIN and SNOUT for test interpretation."],
        ["Breaking bad news", "Capacity assessment", "Shared decision-making"],
        ["2x2 diagnostic table", "Kübler-Ross model", "Consultation model"],
        ["Bias types", "Study designs", "Ethical principles"],
        ["BRS Behavioral Science", "GMC ethics guidance", "WHO patient safety resources"],
    ),
    "Public Health": _subject(
        "Pre-clinical",
        ["Epidemiology", "Screening", "Health systems", "Prevention"],
        ["Incidence measures new cases; prevalence measures existing cases.", "Good screening needs important disease, accepted test, and effective treatment.", "Herd immunity reduces transmission in populations."],
        ["Diabetes and obesity are major Gulf public health priorities.", "Vaccination programs prevent outbreaks.", "Social determinants shape health outcomes."],
        ["Diabetes mellitus", "Hypertension", "Obesity", "Tuberculosis"],
        ["Vaccines, antihypertensives, statins, metformin as population-relevant prevention tools."],
        ["Prevention levels: primordial, primary, secondary, tertiary.", "Odds ratio approximates relative risk in rare disease."],
        ["Counselling for lifestyle change", "Screening advice", "Outbreak investigation"],
        ["Epidemic curve", "Screening pathway", "Health promotion pyramid"],
        ["Study designs", "Screening test metrics", "Vaccine schedules"],
        ["WHO", "Oman Ministry of Health", "CDC epidemiology resources"],
    ),
    "Forensic Medicine": _subject(
        "Pre-clinical",
        ["Death certification", "Injuries", "Toxicology", "Medical law"],
        ["Rigor mortis, livor mortis, and algor mortis help estimate time since death.", "Patterned bruises may indicate object shape.", "Chain of custody protects evidence integrity."],
        ["Carbon monoxide poisoning causes tissue hypoxia.", "Non-accidental injury requires safeguarding response.", "Alcohol intoxication affects consent and capacity."],
        ["Poisoning", "Burns", "Asphyxia", "Non-accidental injury"],
        ["Naloxone, activated charcoal in selected cases, antidotes such as N-acetylcysteine for paracetamol."],
        ["HOP: history, observations, preservation of evidence.", "ABCD applies first: resuscitate before forensic detail."],
        ["Document injuries", "Death certificate scenario", "Consent and capacity station"],
        ["Bruise aging caveats", "Wound types", "Toxicology pathways"],
        ["Injury types", "Common antidotes", "Medico-legal documents"],
        ["Knight's Forensic Pathology", "Local legal guidance", "WHO violence resources"],
    ),
    "Internal Medicine": _subject(
        "Clinical",
        ["Cardiology", "Respiratory", "Gastroenterology", "Endocrinology and nephrology"],
        ["Chest pain assessment prioritizes ACS, PE, aortic dissection, pneumothorax, and esophageal rupture.", "AKI is pre-renal, intrinsic, or post-renal.", "DKA has hyperglycemia, ketones, and acidosis."],
        ["STEMI requires urgent reperfusion.", "Cirrhosis causes portal hypertension and synthetic dysfunction.", "Hyperkalemia can cause life-threatening arrhythmias."],
        ["Myocardial infarction", "COPD", "Cirrhosis", "CKD", "DKA"],
        ["Aspirin, statins, insulin, bronchodilators, diuretics, anticoagulants."],
        ["MONA is old shorthand for MI support; prioritize guideline-based ACS pathway.", "AEIOU: dialysis indications."],
        ["Chest pain history", "Diabetic review", "Respiratory exam", "Abdominal exam"],
        ["ECG territories", "CXR patterns", "Renal tubular disorders"],
        ["Anemia workup", "LFT patterns", "Electrolyte emergencies"],
        ["Harrison's", "Oxford Handbook of Clinical Medicine", "NICE/ESC/GOLD guidelines"],
    ),
    "Surgery": _subject(
        "Clinical",
        ["Acute abdomen", "Trauma", "Perioperative care", "Surgical subspecialties"],
        ["Appendicitis classically migrates from periumbilical pain to right iliac fossa pain.", "ABCDE assessment comes before definitive diagnosis in trauma.", "Postoperative fever timing narrows differential."],
        ["Bowel obstruction causes colicky pain, vomiting, distension, and constipation.", "Compartment syndrome requires urgent fasciotomy.", "Sepsis source control is surgical when infection is drainable."],
        ["Appendicitis", "Cholecystitis", "Bowel obstruction", "Hernia"],
        ["Analgesia, antibiotics, VTE prophylaxis, fluids, anesthesia drugs."],
        ["5 Ws of postoperative fever: wind, water, wound, walking, wonder drugs.", "ABCDE trauma."],
        ["Acute abdomen exam", "Surgical consent", "Wound assessment"],
        ["Appendix positions", "Hernia anatomy", "Trauma primary survey"],
        ["Acute abdomen differentials", "Shock types", "Post-op complications"],
        ["Bailey & Love", "ATLS", "SAGES guidelines"],
    ),
    "Pediatrics": _subject(
        "Clinical",
        ["Growth and development", "Neonatology", "Pediatric infections", "Emergency pediatrics"],
        ["Children are not small adults: dosing is weight-based.", "Dehydration severity is assessed clinically.", "Developmental milestones screen neurologic and social progress."],
        ["Bronchiolitis causes feeding difficulty, wheeze, and increased work of breathing.", "Kawasaki disease risks coronary aneurysms.", "Meningitis may present nonspecifically in infants."],
        ["Bronchiolitis", "Asthma", "Gastroenteritis", "Kawasaki disease"],
        ["Paracetamol, salbutamol, antibiotics by weight, vaccines, oral rehydration solution."],
        ["SAMPLE pediatric history.", "ABCDE plus glucose in sick child."],
        ["Pediatric respiratory exam", "Newborn exam", "Growth chart interpretation"],
        ["Growth chart", "Neonatal circulation", "Immunization schedule"],
        ["Milestones", "Pediatric emergencies", "Dehydration signs"],
        ["Nelson Pediatrics", "WHO child health", "AAP resources"],
    ),
    "Obstetrics & Gynecology": _subject(
        "Clinical",
        ["Antenatal care", "Labor and delivery", "Gynecologic disorders", "Reproductive endocrinology"],
        ["Ectopic pregnancy must be considered in reproductive-age abdominal pain.", "Pre-eclampsia is hypertension after 20 weeks with proteinuria or organ dysfunction.", "Postpartum hemorrhage is a leading obstetric emergency."],
        ["Shoulder dystocia requires structured maneuvers.", "PCOS causes oligo-ovulation and hyperandrogenism.", "Endometriosis causes cyclical pelvic pain."],
        ["Ectopic pregnancy", "Pre-eclampsia", "Postpartum hemorrhage", "PCOS"],
        ["Oxytocin, magnesium sulfate, methyldopa/labetalol, contraceptives, folic acid."],
        ["HELLP: hemolysis, elevated liver enzymes, low platelets.", "4 Ts of PPH: tone, trauma, tissue, thrombin."],
        ["Obstetric history", "Antenatal counselling", "Pelvic pain station"],
        ["Fetal circulation", "Partograph", "Pelvic anatomy"],
        ["Causes of bleeding in pregnancy", "Contraception methods", "Hypertensive disorders"],
        ["Williams Obstetrics", "RCOG Green-top Guidelines", "WHO maternal health"],
    ),
    "Psychiatry": _subject(
        "Clinical",
        ["Mood disorders", "Psychosis", "Anxiety and trauma", "Risk assessment"],
        ["Major depression requires persistent low mood or anhedonia plus associated symptoms.", "Mania includes elevated mood, reduced sleep, and functional impairment.", "Always assess suicide risk directly."],
        ["Delirium has acute fluctuating attention impairment.", "First-rank psychotic symptoms need careful history.", "Substance use can mimic psychiatric disease."],
        ["Depression", "Bipolar disorder", "Schizophrenia", "Delirium"],
        ["SSRIs, lithium, antipsychotics, benzodiazepines short term, mood stabilizers."],
        ["SIGECAPS for depression.", "DIGFAST for mania."],
        ["Mental state examination", "Suicide risk assessment", "Capacity assessment"],
        ["MSE framework", "Biopsychosocial model", "Sleep cycle"],
        ["Antidepressant adverse effects", "Psychosis differentials", "Risk factors"],
        ["DSM-5-TR", "Oxford Handbook of Psychiatry", "NICE mental health guidance"],
    ),
    "Emergency Medicine": _subject(
        "Clinical",
        ["Resuscitation", "Trauma", "Toxicology", "Common ED presentations"],
        ["ABCDE stabilizes life threats before diagnosis.", "Sepsis treatment requires early recognition, cultures, antibiotics, fluids, and source control.", "Time-critical diagnoses include MI, stroke, PE, sepsis, and ectopic pregnancy."],
        ["Anaphylaxis requires IM adrenaline.", "Status epilepticus requires benzodiazepine then second-line therapy.", "Opioid overdose responds to naloxone."],
        ["Sepsis", "Anaphylaxis", "Stroke", "Pulmonary embolism"],
        ["Adrenaline, naloxone, benzodiazepines, thrombolytics, broad-spectrum antibiotics."],
        ["ABCDE.", "H's and T's for reversible cardiac arrest causes."],
        ["Primary survey", "Basic life support", "Sepsis handover"],
        ["ALS algorithm", "Shock classification", "Triage scale"],
        ["Emergency drugs", "Trauma priorities", "Chest pain pathway"],
        ["Tintinalli Emergency Medicine", "Resuscitation Council guidance", "ATLS/ACLS"],
    ),
    "Radiology": _subject(
        "Clinical",
        ["Chest imaging", "Abdominal imaging", "Neuroimaging", "MSK imaging"],
        ["Always check patient, projection, rotation, inspiration, exposure on CXR.", "CT head first excludes hemorrhage in acute stroke pathways.", "Ultrasound is first-line for gallstones and many obstetric questions."],
        ["Pneumothorax shows absent lung markings beyond pleural line.", "Small bowel obstruction shows dilated loops and air-fluid levels.", "Extradural hematoma is classically biconvex."],
        ["Pneumonia", "Pneumothorax", "Bowel obstruction", "Intracranial hemorrhage"],
        ["Contrast safety: assess renal function, allergy history; consider metformin rules by local protocol."],
        ["ABCDE for CXR: airway, bones, cardiac, diaphragm, everything else.", "Blood Can Be Very Bad: CT blood density changes over time."],
        ["CXR interpretation", "CT head interpretation", "Explain imaging risks"],
        ["CXR zones", "CT brain hemorrhage types", "Abdominal X-ray gas patterns"],
        ["Imaging modalities", "CXR signs", "Fracture descriptions"],
        ["Felson CXR", "Radiopaedia", "ACR Appropriateness Criteria"],
    ),
    "Dermatology": _subject(
        "Clinical",
        ["Lesion morphology", "Inflammatory dermatoses", "Infections", "Skin cancers"],
        ["Describe skin lesions by site, distribution, morphology, color, and surface.", "ABCDE helps screen melanoma.", "Psoriasis plaques are well-demarcated with silvery scale."],
        ["Atopic eczema is itchy and flexural.", "Cellulitis is warm, tender, spreading erythema.", "Stevens-Johnson syndrome is a drug-related emergency."],
        ["Eczema", "Psoriasis", "Cellulitis", "Melanoma"],
        ["Topical steroids by potency, emollients, antihistamines, antibiotics, isotretinoin monitoring."],
        ["ABCDE melanoma.", "The 6 Ps of lichen planus: planar, purple, polygonal, pruritic, papules, plaques."],
        ["Skin lesion description", "Counsel topical steroid use", "Mole assessment"],
        ["Skin layers", "Primary lesions", "Dermatomes"],
        ["Rashes by morphology", "Topical steroid potency", "Skin cancer features"],
        ["Rook Dermatology", "DermNet NZ", "BAD guidelines"],
    ),
    "ENT": _subject(
        "Clinical",
        ["Ear disorders", "Nose and sinuses", "Throat", "Head and neck emergencies"],
        ["Acute otitis media causes bulging erythematous tympanic membrane.", "Conductive hearing loss has abnormal Rinne and Weber lateralizes to affected ear.", "Stridor is an airway warning sign."],
        ["Peritonsillar abscess causes trismus and uvular deviation.", "Epistaxis is often anterior from Kiesselbach plexus.", "Vestibular neuritis causes prolonged vertigo without hearing loss."],
        ["Otitis media", "Sinusitis", "Epistaxis", "Peritonsillar abscess"],
        ["Amoxicillin when indicated, topical nasal steroids, adrenaline in airway emergencies, antiemetics for vertigo."],
        ["Rinne: AC greater than BC is normal.", "NO TEARS for epistaxis initial management: nose pinch, observe, topical vasoconstrictor, etc."],
        ["Otoscopy", "Hearing tests", "Epistaxis management"],
        ["Middle ear anatomy", "Sinus drainage", "Larynx anatomy"],
        ["Hearing loss types", "Neck lumps", "Vertigo differentials"],
        ["Scott-Brown ENT", "ENT UK", "BMJ Best Practice"],
    ),
    "Ophthalmology": _subject(
        "Clinical",
        ["Red eye", "Vision loss", "Retina", "Neuro-ophthalmology"],
        ["Painful red eye with reduced vision is urgent.", "Acute angle closure glaucoma causes severe pain, halos, mid-dilated pupil.", "Diabetic retinopathy screening prevents vision loss."],
        ["Central retinal artery occlusion causes sudden painless monocular vision loss.", "Retinal detachment may cause flashes, floaters, curtain shadow.", "Optic neuritis causes painful visual loss."],
        ["Conjunctivitis", "Glaucoma", "Diabetic retinopathy", "Retinal detachment"],
        ["Topical antibiotics, lubricants, timolol/latanoprost, acetazolamide, steroids by specialist advice."],
        ["Painful red eye danger: glaucoma, keratitis, uveitis, scleritis.", "Marcus Gunn pupil suggests optic nerve disease."],
        ["Visual acuity", "Pupillary reflexes", "Fundoscopy"],
        ["Eye anatomy", "Visual pathway", "Retinal layers"],
        ["Red eye differentials", "Vision loss causes", "Glaucoma medications"],
        ["Kanski Ophthalmology", "AAO EyeWiki", "NICE CKS eye conditions"],
    ),
    "Orthopedics": _subject(
        "Clinical",
        ["Fractures", "Joint disease", "Spine", "Sports injuries"],
        ["Always document neurovascular status before and after reduction.", "Open fractures need antibiotics and urgent surgical assessment.", "Cauda equina is a spinal emergency."],
        ["Hip fracture causes shortened externally rotated leg.", "Septic arthritis is a hot swollen joint emergency.", "Osteoarthritis pain worsens with use."],
        ["Hip fracture", "Septic arthritis", "Osteoarthritis", "Compartment syndrome"],
        ["Analgesia, antibiotics for open fractures, anticoagulation prophylaxis, bisphosphonates for osteoporosis."],
        ["Ottawa ankle rules guide X-ray need.", "5 Ps of compartment syndrome: pain, pallor, pulselessness, paresthesia, paralysis."],
        ["Joint exam", "Back pain red flags", "Neurovascular limb assessment"],
        ["Bone healing", "Dermatomes", "Common fractures"],
        ["Fracture description", "Arthritis comparison", "Back pain red flags"],
        ["Apley Orthopedics", "BOAST guidelines", "AO Surgery Reference"],
    ),
    "Anesthesiology": _subject(
        "Clinical",
        ["Airway", "General anesthesia", "Regional anesthesia", "Pain medicine"],
        ["Airway assessment predicts difficult intubation risk.", "Malignant hyperthermia is triggered by volatile agents and succinylcholine.", "Local anesthetic systemic toxicity can cause seizures and arrhythmias."],
        ["Rapid sequence induction reduces aspiration risk.", "Spinal anesthesia can cause hypotension.", "Opioids cause respiratory depression."],
        ["Difficult airway", "Malignant hyperthermia", "Postoperative nausea", "Pain crisis"],
        ["Propofol, ketamine, etomidate, volatile agents, opioids, neuromuscular blockers, local anesthetics."],
        ["LEMON for difficult airway assessment.", "SOAP ME for airway preparation."],
        ["Airway assessment", "Pre-op assessment", "Pain score management"],
        ["Airway anatomy", "Dermatomes for spinal anesthesia", "Anesthetic machine basics"],
        ["Induction agents", "Neuromuscular blockers", "Local anesthetic toxicity"],
        ["Miller's Anesthesia", "DAS airway guidelines", "WFSA resources"],
    ),
    "Family Medicine": _subject(
        "Clinical",
        ["Primary care consultation", "Chronic disease", "Preventive medicine", "Community health"],
        ["Family medicine integrates biomedical, psychological, and social context.", "Continuity improves chronic disease management.", "Safety-netting is essential when diagnosis is uncertain."],
        ["Hypertension management includes lifestyle and risk-based medication.", "Diabetes care includes HbA1c, BP, lipids, renal, eye, and foot review.", "Back pain needs red flag screening."],
        ["Hypertension", "Diabetes", "Asthma", "Depression"],
        ["Metformin, statins, antihypertensives, inhalers, vaccines, smoking cessation medicines."],
        ["ICE: ideas, concerns, expectations.", "BATHE: background, affect, trouble, handling, empathy."],
        ["Primary care consultation", "Chronic disease review", "Lifestyle counselling"],
        ["Cardiovascular risk pathway", "Diabetic annual review", "Family genogram"],
        ["Screening schedule", "Chronic disease targets", "Red flags"],
        ["Oxford Handbook of General Practice", "USPSTF", "Oman MOH primary care guidance"],
    ),
}


SUBJECT_ORDER = list(AZ_MEDICAL_KNOWLEDGE.keys())
